PICKS = [
 # bloco 1 — pré-lead
 (0,   "apresentador_podcast_microfone", "Abertura: apresentador de camisa escura no estúdio de podcast com microfone"),
 (8,   "ator_ex_brazzers_rasga_contrato", "Ator pornô ex-Brazzers no estúdio rasgando um 'CONTRACT'; lettering 'UNDER CONTRACT'"),
 (24,  "anatomia_corpo_transparente_coracao", "Animação 3D de corpo humano transparente com coração iluminado; lettering 'BECAUSE IF SOMETHING'"),
 (36,  "broll_porno_atriz_tatuada", "B-roll pornô explícito (atriz tatuada); lettering 'FOR UP TO TWO HOURS'"),
 (49,  "caixa_tadalafil_sandoz_20mg", "Ator no estúdio segurando caixa de 'Tadalafil Sandoz 20 mg'; lettering 'CIALIS OR TADALAFIL PILL'"),
 (51,  "cavalo_estabulo_mao", "Cavalo no estábulo recebendo comida na mão; lettering 'ALL IS A SPECIAL HORSE'"),
 (54,  "animacao_3d_penis_vasos", "Animação 3D do pênis e testículos com vasos sanguíneos; lettering 'THE BEST PART?'"),
 (61,  "cientista_touca_oculos_mascara", "Cientista de touca azul, óculos e máscara; lettering 'THAT STUDIES SHOWED A 342%'"),
 (74,  "animacao_3d_prostata_aumentada", "Animação 3D da próstata e bexiga; lettering 'ENLARGED PROSTATE.'"),
 (76,  "bomba_peniana_vermelha", "Bomba peniana (cilindro transparente) em uso; lettering 'NO PENIS PUMPS,'"),
 (80,  "fita_metrica_amarela_calca", "Fita métrica amarela sobre o volume da calça; lettering 'ONLY PROBLEM'"),
 (94,  "apresentador_pede_video_dr_brazza", "Apresentador no estúdio; lettering 'BRAZZERS VIDEO HERE?'"),
 # bloco 2 — lead
 (100, "lettering_one_spoonful_gelatina_rosa", "Narrador (Dr. Peter Attia) segurando gelatina rosa translúcida; lettering 'ONE SPOONFUL OF THIS GELATINE IS UP TO'"),
 (102, "lettering_6x_more_potent", "Narrador em cozinha; lettering '6X MORE POTENT AND EFFECTIVE'"),
 (104, "gelatina_pyrex_limao_mesa", "Jarra Pyrex com gelatina vermelha, limão e ingredientes na mesa; legenda 'This gelatin, taken'"),
 (114, "lettering_simple_as_that", "Tela escura com lettering verde 'SIMPLE AS THAT'"),
 (116, "po_gelatina_despejado_tigela", "Pó de gelatina sendo despejado em tigela de vidro; legenda 'and introducing'"),
 (130, "colagem_broll_porno_3_cenas", "Colagem com 3 cenas pornô; legenda 'have already tested it'"),
 (136, "dna_azul_genetica", "Animação de DNA azul; legenda 'with different genetics,'"),
 (138, "idoso_bebendo_cerveja", "Idoso grisalho bebendo cerveja; legenda 'lifestyles'"),
 (142, "lettering_literally_for_anyone", "Narrador ao fundo escuro; lettering 'LITERALLY FOR ANYONE'"),
 (148, "johnny_sins_cozinha_jello", "Ator careca (Johnny Sins) na cozinha mexendo tigela com caixas de Jell-O; legenda 'On top of that,'"),
 (156, "corpo_cavernoso_dildo_mao", "Dildo realista segurado na mão; legenda 'to the corpus cavernous'"),
 (167, "volume_calca_branca_bulge", "Volume na calça branca; legenda 'giving that bulge'"),
 (178, "lettering_this_gelatine_is_6x", "Tela laranja com lettering 'THIS GELATINE IS 6X'"),
 (186, "idoso_grisalho_xicara_amarela", "Homem grisalho bebendo em xícara amarela; legenda 'also completely'"),
 (198, "lettering_has_the_power_to_bring_down", "Narrador em tom vermelho; lettering 'HAS THE POWER TO BRING DOWN'"),
 (203, "caixa_viagra_100mg_pfizer", "Caixa de Viagra 100 mg (Pfizer) em fundo escuro; legenda 'behind the Viagra,'"),
 (219, "cientista_tubo_azul_193_artigos", "Cientista de máscara segurando tubo de ensaio azul; legenda 'More than 193'"),
 (226, "pesquisador_microscopio", "Pesquisador de jaleco no microscópio; legenda 'along with the'"),
 (233, "idoso_barba_branca_idade", "Idoso de barba branca; legenda 'isn't related to age,'"),
 (235, "moleculas_3d_hormonios", "Animação 3D de moléculas; legenda 'hormone levels,'"),
 (239, "lettering_toxic_plaques_vermelho", "Fundo vermelho com células; lettering 'TOXIC PLAQUES'"),
 (243, "animacao_3d_arteria_corte", "Animação 3D de artéria em corte; legenda 'Over the last 30 years,'"),
 (248, "lettering_and_whoever_did_this_has_a_name", "Tela escura; lettering 'AND WHOEVER DID THIS HAS A NAME'"),
 (251, "narrador_dr_peter_attia_stanford", "Narrador (Dr. Peter Attia) em tom laranja; legenda 'And as a Stanford'"),
 (265, "gomas_vermelhas_prato_branco", "Mão segurando goma vermelha sobre prato com várias gomas; legenda 'when you wake up'"),
 # bloco 3 — depoimentos
 (280, "depoimento_arnold_homem_78_anos", "Depoimento 'homem de 78 anos' (imagem de Arnold Schwarzenegger em jardim, tom laranja); legenda 'I started using this'"),
 (296, "depoimento_arnold_fucking_like_30", "Mesmo depoimento (Arnold); legenda 'I was 30.'"),
 (318, "depoimento_mulher_morena_cabelo_longo", "Depoimento de mulher morena de cabelo longo (namorada), tom laranja; legenda 'the more they come back.'"),
 (323, "depoimento_namorada_sex_of_my_life", "Mulher morena em cozinha falando à câmera; legenda 'sex of my life.'"),
 (341, "narrador_i_received_testimonials", "Narrador (Dr. Peter Attia) no estúdio; legenda 'I received testimonials'"),
 (352, "gelatina_rosa_despejada_tigela", "Gelatina rosa líquida sendo despejada em tigela; legenda 'because you're going'"),
 (367, "lettering_big_and_hard_as_a_rock", "Narrador ao fundo escuro; lettering vermelho 'BIG AND HARD AS A ROCK'"),
 (374, "broll_porno_finally_unlocking", "B-roll pornô explícito; legenda 'Finally unlocking'"),
 # bloco 4 — quem é o Dr. Peter Attia
 (384, "peter_attia_palestra_poltrona", "Dr. Peter Attia de terno em poltrona num evento com microfone; legenda 'I am Doctor Peter Attia.'"),
 (387, "logo_stanford_university", "Selo 'STANFORD UNIVERSITY'; legenda 'from Stanford University.'"),
 (392, "cirurgia_sala_operacao", "Cena de cirurgia em sala de operação; legenda 'I operated on pancreas'"),
 (404, "early_medical_clinica_tela", "Painel 'Early Medical' (clínica do Dr. Attia, 'Medicine 3.0'); legenda 'I built what is today'"),
 (408, "atleta_academia_regata_verde", "Atleta treinando de regata verde na academia; legenda 'performance and extension'"),
 (415, "attia_com_chris_hemsworth", "Dr. Attia ao lado de Chris Hemsworth; legenda 'Hollywood actors'"),
 (419, "attia_com_stallone_foto", "Foto de Sylvester Stallone e Dr. Attia sorrindo; legenda 'at 60 years old.'"),
 (426, "podcast_the_drive_card", "Card do podcast com foto do Dr. Attia; legenda 'top five in'"),
 (432, "attia_podcast_microfone", "Dr. Attia gravando podcast com microfone; legenda 'I interview scientists,'"),
 (439, "attia_microfone_polo", "Dr. Attia de polo com microfone em evento; legenda 'hormone, mitochondria.'"),
 (457, "histologia_roxa_tecido", "Lâmina histológica roxa; legenda 'every American man over 40,'"),
 (480, "stallone_e_attia_academia_selfie", "Stallone e Dr. Attia na academia (selfie no espelho); legenda 'Our kids grew up together.'"),
 (485, "stallone_sem_camisa_tatuagens", "Stallone sem camisa, musculoso; legenda '79 years old.'"),
 (487, "stallone_rambo_cena", "Stallone como Rambo; legenda 'Rocky Rambo,'"),
 (489, "stallone_rocky_luvas_vermelhas", "Stallone como Rocky com luvas vermelhas; legenda 'of American cinema'"),
 (504, "stallone_academia_remada", "Stallone treinando remada com anilhas; legenda 'I've seen him eat.'"),
 # bloco 5 — a ligação de sábado
 (517, "celular_ligacao_stallone", "Celular com chamada recebida de Sylvester Stallone; legenda 'In October of 2025,'"),
 (528, "lettering_i_canceled_3_podcasts", "Narrador; lettering vermelho 'I CANCELED 3 PODCASTS'"),
 (547, "stallone_attia_academia_after_15_years", "Stallone e Dr. Attia na academia; legenda 'after 15 years'"),
 (554, "stallone_academia_cabos", "Stallone treinando com cabos na academia; legenda 'And when I hung up the phone'"),
 (570, "nutricionista_prancheta", "Mão escrevendo em prancheta; legenda 'the best nutritionist,'"),
 (574, "stallone_jovem_sem_camisa", "Stallone jovem sem camisa com corrente; legenda 'on the planet at his disposal,'"),
 (581, "lettering_without_a_name_idoso", "Idoso de barba branca com a mão no rosto; lettering vermelho 'WITHOUT A NAME.'"),
 (588, "cirurgiao_notas_de_dolar", "Cirurgião de máscara segurando notas de dólar; legenda 'in the world.'"),
 (604, "livro_antigo_registros", "Livro antigo de registros manuscritos; legenda 'and what I found in'"),
 (614, "stallone_sentado_jaqueta_preta", "Stallone sentado ao ar livre de jaqueta preta; legenda 'what he told me that Saturday,'"),
 # bloco 6 — Stallone I
 (625, "stallone_selfie_pete_told_me", "Stallone em selfie, camisa marrom; lettering 'Peter told me I'"),
 (635, "stallone_retrato_terno", "Retrato de Stallone de terno escuro; legenda 'I made it to 79 years old.'"),
 (657, "jennifer_cama_celular", "Mulher morena de preto na cama olhando o celular; legenda 'and she was already'"),
 (664, "casal_cama_pijama_virada", "Casal na cama: homem de pijama preto e mulher virada; legenda 'with that'"),
 (686, "stallone_but_id_lie_there_awake", "Stallone falando à câmera; legenda 'But I'd lie there awake,'"),
 (693, "stallone_jennifer_foto_praia", "Foto antiga de Stallone e Jennifer Flavin de maiô; legenda 'and thinking'"),
 (710, "broll_porno_carro", "B-roll pornô explícito em carro; legenda 'when she wanted me'"),
 (722, "idoso_consulta_urologista", "Idoso em consulta com médico; legenda 'So I did what a man'"),
 (727, "comprimidos_azuis_viagra", "Comprimidos azuis em blister; legenda 'in 2020.'"),
 (758, "casal_beijo_pescoco", "Homem beijando o pescoço de mulher ruiva; legenda 'She let me kissed her neck.'"),
 (772, "mao_penis_flacido_it_bent", "Mão segurando pênis flácido; legenda 'It bent'"),
 (807, "capsulas_azuis_warm_from_the_drug", "Cápsulas azuis e brancas; legenda 'warm from the drug'"),
 (811, "animacao_arteria_placas_verdes", "Animação de artéria rosa com placas verdes; legenda 'where it needed to go.'"),
 (821, "stallone_tapete_vermelho_film_review", "Stallone de terno em tapete vermelho; legenda 'More than a film review.'"),
 (823, "stallone_tribunal_lawsuit", "Stallone em tribunal; legenda 'More than a lawsuit.'"),
 (827, "stallone_ex_esposas_colagem", "Colagem de Stallone com ex-esposas; legenda 'from the other two marriages.'"),
]
