PICKS = [
 # bloco 7 — Stallone II
 (838, "bandeja_trt_seringa_frasco", "Bandeja com seringa, frasco de testosterona e receita de TRT; legenda 'I tried to'"),
 (841, "frasco_testosterone_cypionate_trt", "Frasco 'Testosterone Cypionate' e seringa sobre receita 'TRT'; legenda 'testosterone replacement'"),
 (847, "penis_flacido_the_dysfunction", "Close de pênis flácido na mão; legenda 'The dysfunction'"),
 (852, "homem_grisalho_esteira_fones", "Homem grisalho de regata correndo na esteira com fones; legenda 'I started avoiding the gym,'"),
 (854, "fachada_equinox_beverly_hills", "Fachada da academia Equinox; legenda 'the Equinox in Beverly Hills.'"),
 (866, "homem_nu_vestiario_slapping", "Homem nu no vestiário (corpo inteiro); legenda 'slapping against his thigh,'"),
 (876, "stallone_saindo_academia_bolsa", "Stallone saindo de prédio com bolsa, acompanhado; legenda 'I was at a cafe in Beverly'"),
 (885, "casal_caminhando_de_maos_dadas", "Casal de costas caminhando de mãos dadas (homem grisalho, mulher de vestido floral); legenda 'He was about 50.'"),
 (893, "jennifer_e_homem_cafe_le_petit_coin", "Mulher loira de casaco branco com homem grisalho em frente ao café 'Le Petit Coin'; legenda 'about four meters from mine,'"),
 (899, "mulher_loira_amigas_mesa_vinho", "Mulher loira com amigas à mesa com taças de vinho; legenda 'Then the'"),
 (910, "homem_mao_dentro_da_calca_dela", "Homem com a mão na cintura/calça da mulher loira ao lado da mesa; legenda 'inside her pants,'"),
 (914, "camera_seguranca_cafe_casal", "Imagem de câmera de segurança do café com o casal (data 10-14-2024); legenda 'His hand'"),
 (945, "mao_homem_quadril_mulher", "Close da mão do homem no quadril da mulher; legenda 'Her hip tilted in that'"),
 (970, "mulher_loira_amigas_olhando_camera", "Mulher loira e amigas à mesa olhando para a câmera; legenda 'He's more of a'"),
 (984, "stallone_terno_preto_chuva_rua", "Stallone de terno preto andando na rua sob chuva; legenda 'inside my own clothes.'"),
 (989, "stallone_on_doctor_peters_door", "Stallone falando à câmera (relógio Apple Watch); legenda 'on Doctor Peter's door.'"),
 # bloco 8 — investigação
 (999, "stallone_cafe_triste_jaqueta", "Stallone sentado em café, abatido; legenda 'Sylvester wasn't failing.'"),
 (1002, "attia_maos_no_rosto", "Dr. Attia com as mãos no rosto; legenda 'The system was failing him'"),
 (1005, "attia_palestra_camisa_xadrez", "Dr. Attia palestrando de camisa xadrez; legenda 'in male longevity,'"),
 (1014, "cirurgia_peniana_luvas", "Cena de cirurgia com luvas azuis; legenda 'to penile surgery.'"),
 (1028, "attia_lendo_livro_mesa", "Dr. Attia lendo livro à mesa; legenda 'I locked the door of my office'"),
 (1035, "notas_100_dolares_350000", "Notas de $100 enfileiradas; legenda 'threw out $350,000'"),
 (1045, "mesa_monitores_pubmed_cochrane", "Mesa com monitores (PubMed, Cochrane) e papéis; legenda 'Private repositories'"),
 (1068, "attia_laptop_noite", "Dr. Attia trabalhando no laptop à noite; legenda 'every single one'"),
 (1073, "pilhas_dinheiro_pfizer_lilly", "Pilhas de dinheiro com logos Pfizer e Eli Lilly; legenda 'Pfizer, Bayer and Eli Lilly.'"),
 (1079, "cientista_pipeta_vidro", "Cientista de óculos com pipeta; legenda 'by the guys who sell the pill.'"),
 (1085, "idoso_grisalho_estresse", "Idoso grisalho com a mão no rosto; legenda 'It wasn't in stress.'"),
 (1092, "galao_roundup_360_plus", "Galão de Roundup 360 Plus; lettering vermelho 'ROUNDUP'"),
 (1094, "pulverizador_amarelo_plantacao", "Pulverizador amarelo em plantação; legenda 'on the planet.'"),
 (1097, "logo_bayer_cruz_noite", "Logo da Bayer iluminado; legenda 'Monsanto since 1974.'"),
 (1100, "infografico_97_usda_glifosato", "Infográfico 'In 2024, 97% of American food samples tested by the USDA... contained glyphosate' (97%)"),
 (1109, "mesa_cattle_feed_quaker_glyphosate_results", "Mesa com saco 'Cattle Feed', aveia Quaker, cerveja, leite e papel 'Glyphosate Detection Results 97%'"),
 (1117, "attia_it_accumulates_in_fatty_tissue", "Dr. Attia; legenda 'It accumulates in fatty tissue,'"),
 (1120, "vasos_vermelhos_tecido_penis", "Animação de vasos vermelhos; legenda 'tissue of your penis.'"),
 (1122, "hamburguer_grelha_fogo", "Hambúrgueres na grelha; legenda 'the last 40 years'"),
 (1127, "wsj_bayer_24_billion_roundup", "Capa do The Wall Street Journal: 'Bayer Faces $24 Billion in Combined Roundup Settlements'; legenda 'consecutive settlements'"),
 (1129, "journal_bayer_24_billion_roundup", "Revista 'The Journal' com mesma manchete sobre $24 bilhões da Bayer; legenda 'about cancer.'"),
 (1140, "microscopio_luvas_azuis_11_cientistas", "Laboratório com microscópio e luvas azuis; legenda 'of 11 internal scientists.'"),
 # bloco 9 — FDA / memo / Big Pharma
 (1146, "attia_i_talked_to_one", "Dr. Attia; legenda 'I talked to one,'"),
 (1169, "carimbo_top_secret_documento", "Documento com carimbo vermelho; legenda 'stamped confidential'"),
 (1183, "memo_04_beta_bayer_confidential", "Documento 'Bayer AG — Confidential Internal Memo 04-BETA' em tela; legenda 'They knew in 1998,'"),
 (1185, "memo_04_beta_paginas_abertas", "Páginas do Memo 04-BETA (efeitos do glifosato em tecido erétil de ratos); legenda 'they discussed it'"),
 (1188, "memo_04_beta_tabelas_histologia", "Páginas do memo com tabelas e histologia; legenda 'It publicly'"),
 (1195, "logo_pfizer_parede", "Logo Pfizer na parede ('Breakthroughs that change patients' lives'); legenda 'Pfizer pulls'"),
 (1203, "levitra_cialis_another_4_billion", "Caixas de Levitra e Cialis; lettering vermelho 'ANOTHER 4 BILLION'"),
 (1216, "attia_tom_laranja_i_got_a_call", "Dr. Attia em tom laranja; legenda 'I got a call.'"),
 (1218, "macos_de_dolares_formula", "Maços de notas de $100; legenda 'for the formula'"),
 (1222, "selo_top_secret_nda", "Selo 'TOP SECRET' em documento; legenda 'under a permanent NDA.'"),
 (1224, "facebook_video_removed", "Tela do Facebook 'Video removed'; legenda 'This video has been censored'"),
 (1228, "youtube_video_removed", "Tela do YouTube 'Video removed'; legenda 'in the last four months.'"),
 (1245, "ex_executivo_pfizer_depoimento_borrado", "Depoimento com rosto borrado: 'Former Senior Marketing Director, Pfizer, 2007-2021'; legenda 'Maintenance is the product.'"),
 # bloco 10 — Bill Gates / carrapato
 (1247, "pulverizando_horta_roundup", "Pessoa pulverizando horta com galão de Roundup; legenda 'natural way out of glyphosate'"),
 (1253, "mural_cdc_lone_star_tick_mapa", "Mural com mapa 'CDC confirmed: Lone Star tick detected in 53 states' e foto do carrapato; legenda 'in 2024,'"),
 (1255, "diagrama_alpha_gal_proteina", "Diagrama da proteína Alpha-Gal; legenda 'the CDC confirmed'"),
 (1257, "jornal_daily_sentinel_lone_star_tick", "Jornal 'Daily Sentinel': 'CDC confirms Lone Star tick now in 53 states, carrying Alpha-Gal protein'"),
 (1259, "jornal_daily_herald_alpha_gal", "Jornal 'The Daily Herald' sobre o carrapato Lone Star e Alpha-Gal; legenda 'called alpha gal.'"),
 (1271, "infografico_bill_gates_11_4_billion", "Infográfico 'Bill Gates $11.4 Billion Investment Portfolio Since 2022' (carrapatos, Beyond Meat, Impossible Foods...)"),
 (1278, "logo_bayer_plantacao", "Logo Bayer sobre plantação; legenda 'to reduce global hunger'"),
 (1285, "bill_gates_beyond_impossible_embalagens", "Bill Gates com embalagens Beyond Burger e Impossible Burger; legenda 'Impossible Foods'"),
 (1291, "comparativo_hamburguer_convencional_vs_plant_based", "Comparativo 'Conventional Beef Burger (low glyphosate)' vs 'Plant-Based Burger (high glyphosate)'"),
 (1295, "colagem_gates_foundation_microsoft", "Colagem Bill & Melinda Gates Foundation / Microsoft / Monsanto; legenda 'This isn't theory.'"),
 (1297, "wsj_dual_profit_machine_bill_gates", "Matéria WSJ 'The Dual Profit Machine: How Bill Gates Benefits From Both Philanthropy and Controversial Investments'"),
 (1300, "sec_form_10k_beyond_meat", "Formulário SEC 10-K da Beyond Meat; legenda 'It's in Beyond Meat's 10-K.'"),
 (1302, "memo_04_beta_buried_post_it", "Documento 'Memo 04-Beta' com carimbo 'BURIED' e post-it; legenda 'It's in the Bayer settlement.'"),
 (1307, "bayer_settlement_agreement_pasta", "Pasta com 'Bayer Settlement Agreement'; legenda 'and it's the link'"),
 (1314, "capsulas_azuis_caixa_big_pharma", "Caixa de cápsulas azuis em fábrica; legenda 'Big Pharma'"),
 (1318, "bill_gates_tom_vermelho_closing_escape", "Bill Gates em tom vermelho; legenda 'closing off the escape.'"),
 # bloco 11 — mecanismo I
 (1338, "animacao_3d_esponja_vasos_sea_sponge", "Animação 3D de tecido com vasos; legenda 'It looks like a sea sponge.'"),
 (1351, "lettering_type_iii_collagen", "B-roll pornô; lettering vermelho 'TYPE III COLLAGEN.'"),
 (1363, "artigo_type_iii_collagen_bladder_1993", "Artigos científicos 'Type III Collagen in the Human Urinary Bladder' (1993) com anotações; legenda 'This data has been documented'"),
 (1366, "journal_of_urology_1993", "Página do Journal of Urology (1993) com imagem de fibras verdes; legenda 'since 1993 in'"),
 (1388, "type_3_collagen_accumulation_diagrama", "Diagrama 'Type 3 Collagen Accumulation' em corte de vaso; legenda 'is mechanically possible,'"),
 (1399, "molecula_glifosato_roundup", "Molécula 3D do glifosato com lettering 'ROUNDUP'; legenda 'that attacks everything equally.'"),
 (1404, "corpo_3d_pulmoes_laranja", "Corpo 3D azul com pulmões em laranja; legenda 'Not your liver, not your lung.'"),
 (1406, "colagenos_tipo_1_2_3_painel", "Painel com colágeno tipo 1, 2 e 3; legenda 'Those tissues have type I'"),
 (1408, "microscopia_glifosato_colageno_iii_verde", "Microscopia 'Glyphosate Binding to Type III Collagen' (verde = glifosato); legenda 'glyphosate passes through'"),
 (1412, "endocrine_reviews_1998_artigo", "Revista Endocrine Reviews (1998) com gráfico de ligação 14x; legenda 'The research,'"),
 (1416, "endocrine_reviews_grafico_14x", "Artigo 'Glyphosate Interactions with Extracellular Matrix Proteins' com gráfico de barras; legenda 'measured this directly.'"),
 (1429, "lettering_your_dick_is_target_number_one", "Dr. Attia; lettering vermelho 'YOUR DICK IS TARGET NUMBER ONE.'"),
 (1431, "agua_tingida_copo_glifosato", "Líquido escuro pingando em copo de água; legenda 'through the glass of water,'"),
 (1433, "caneca_cerveja_mesa", "Caneca de cerveja; legenda 'through the beer.'"),
 (1435, "hemacias_vermelhas_corrente", "Hemácias em animação; legenda 'wall, enters the bloodstream,'"),
 (1451, "fibras_colageno_verde_fluorescente", "Fibras de colágeno com glifosato fluorescente verde; legenda 'three collagen in your dick.'"),
 # bloco 12 — mecanismo II
 (1456, "lettering_oxidative_fibrosis", "Microscopia com lettering vermelho 'OXIDATIVE FIBROSIS.'"),
 (1466, "fibras_onduladas_enegrecidas", "Fibras onduladas com ligações enegrecidas; legenda 'The chemical bonds harden.'"),
 (1475, "fibras_roxas_deposito_verde", "Microscopia roxa com depósito verde; legenda 'damage deposits'"),
 (1483, "type_ii_collagen_diagrama_roxo", "Microscopia roxa com diagrama 'Type II Collagen'; legenda 'It's the same collagen'"),
 (1490, "tecido_cicatriz_fibras_pele", "Tecido de pele com fibras cicatriciais; legenda 'That's the material'"),
 (1502, "bife_americano_garfo_faca", "Bife com garfo e faca; legenda 'Every American steak you ate over'"),
 (1511, "mural_bayer_didnt_poison_you_once", "Mural com recorte 'Bayer didn't poison you once. It poisoned you systematically, meal by meal, for decades.'; legenda 'Moreland 2000.'"),
 (1513, "poster_bayer_pratos_empilhados", "Pôster com pratos empilhados e logo Bayer; legenda 'Sponge turning into scar.'"),
 (1527, "idoso_cabelo_branco_mao_testa", "Idoso de cabelo branco com a mão na testa; legenda 'In stress in age,'"),
 (1536, "lettering_toxic_plaques_microscopia", "Microscopia de esponja com lettering vermelho 'TOXIC PLAQUES'"),
 (1546, "diagrama_corte_penis_placa_toxica", "Diagrama em corte do pênis 'Toxic plaques, hardened deposits of type I collagen over the cavernous tissue' + histologia"),
 (1573, "corte_3d_penis_saudavel", "Corte 3D do pênis com corpo cavernoso saudável; legenda 'is toxic plaque'"),
 (1576, "corte_3d_penis_placas_living_sponge", "Corte 3D do pênis com placas e lupa; legenda 'living sponge.'"),
 (1578, "mangueira_verde_nova_jardim", "Mangueira verde nova sobre grama; legenda 'A new hose is green,'"),
 (1584, "mangueira_jato_agua", "Mangueira jorrando água; legenda 'The hose'"),
 (1592, "mangueira_velha_ressecada_enrolada", "Mangueira velha ressecada enrolada no chão; legenda 'The green rubber turned'"),
 (1595, "mangueira_rachada_cracks", "Mangueira velha com rachaduras; legenda 'There are cracks.'"),
 (1601, "mangueira_vazando_rachadura", "Mangueira vazando pela rachadura; legenda 'cracks at other points'"),
 (1608, "stallone_jennifer_tapete_vermelho", "Stallone e Jennifer Flavin em tapete vermelho; legenda 'sly desire.'"),
 (1624, "mao_feminina_afastando_penis_flacido", "Mão feminina afastando pênis flácido; legenda 'that hurts more than disgust.'"),
 (1634, "microscopia_lado_a_lado_look_at_that_image", "Microscopia lado a lado (tecido saudável rosa x tecido com placas); legenda 'Look at that image.'"),
 (1638, "microscopia_thats_what_she_put_her_hand_on", "Mesma comparação; legenda 'That's what she put her hand on.'"),
]
