PICKS = [
 # bloco 13 — por que nada funcionou
 (1644, "viagra_blister_desenho_peyronie", "Blister de Viagra sobre desenho anotado 'Peyronie's plaque / Viagra doesn't dissolve the scar'; legenda 'Viagra doesn't dissolve the scar.'"),
 (1646, "desenho_viagra_induced_inflow", "Desenho anotado 'Viagra-induced inflow / no tissue compliance' com comprimidos azuis; legenda 'It just forces'"),
 (1655, "trt_protocolo_frasco_seringa", "Protocolo de TRT com frasco e seringa laranja; legenda 'TRT doesn't either.'"),
 (1657, "frasco_testosterona_receita_trt", "Frasco de testosterona cipionato sobre receita; legenda 'Testosterone is the signal.'"),
 (1674, "tecido_cicatriz_endurecida_roxo", "Corte de tecido roxo com cicatriz endurecida branca; legenda 'turned into hardened scar'"),
 (1688, "stand_bayer_monsanto_2018_roundup", "Stand 'Bayer Monsanto 2018' com Roundup e sementes; legenda 'Bayer Monsanto.'"),
 (1690, "bayer_monsanto_merger_2018_grafico", "Gráfico 'Bayer Monsanto Merger 2018' com protestos 'Bayer = Poison'; legenda 'It has a multinational'"),
 (1695, "poster_24_billion_blood_money", "Pôster 'Twenty-Four Billion Dollars already spent silencing cancer lawsuits — Bayer-Monsanto / Blood Money'"),
 (1698, "poster_24_billion_silencing_cancer_lawsuits", "Pôster '$24 Billion already spent silencing cancer lawsuits over the last five years' com logo Bayer"),
 (1714, "trena_amarela_medindo", "Mão com trena amarela medindo; legenda 'that Bayer'"),
 (1718, "notas_dolar_28_billion_market_cap", "Notas de dólar nas mãos; legenda '$28 billion in market'"),
 # bloco 14 — o relógio
 (1728, "corte_penis_saudavel_vs_placas", "Corte do pênis: lado saudável vermelho x lado com placas; legenda 'you crossed the point of no return'"),
 (1736, "stallone_retrato_60_fibrosis", "Retrato de Stallone; legenda 'Stallone had 60% fibrosis'"),
 (1756, "idoso_cabeca_baixa_he_would_have_crossed", "Idoso grisalho de cabeça baixa; legenda 'he would have crossed'"),
 (1767, "mulher_roupao_branco_celular_cama", "Mulher de roupão branco na cama olhando o celular; legenda 'stopped reaching for you,'"),
 (1778, "due_to_toxic_plaque_deposits_laranja", "Comparativo em tom laranja de tecidos; legenda 'due to toxic plaque deposits.'"),
 (1780, "comparativo_corte_tecido_saudavel_placa", "Comparativo: corte 3D saudável x com placas, microscopias abaixo; legenda 'due to toxic plaque deposits.'"),
 (1782, "bife_industrial_garfo", "Bife com garfo; legenda 'Every industrial steak'"),
 (1785, "corte_penis_new_fibrosis_lado_a_lado", "Corte do corpo cavernoso saudável x fibrosado; legenda 'new fibrosis'"),
 (1802, "infografico_glyphosate_enters_through_the_mouth", "Infográfico 'Glyphosate enters through the mouth' (boca → 40 min → corrente sanguínea → 2 h); legenda 'Glyphosate enters'"),
 (1805, "glifosato_verde_vasos_in_two_hours", "Animação de glifosato (verde) nos vasos e fibras; legenda 'In two hours,'"),
 (1810, "glifosato_verde_wont_let_go", "Moléculas verdes aderidas às fibras; legenda 'Won't let go.'"),
 (1818, "fibras_type_three_becomes_type_one", "Painel de fibras de colágeno saudáveis → cicatriz; legenda 'Type three becomes type'"),
 (1821, "fibras_toxic_plaque_hardens", "Painel de fibras com placa tóxica endurecida; legenda 'toxic plaque hardens.'"),
 (1827, "calendario_outubro_485_vezes", "Calendário (October) em close; legenda '485 times per year'"),
 (1830, "simbolo_infinito_9700_vezes", "Símbolo de infinito; legenda '9700 times in 20 years.'"),
 (1849, "mulher_loira_nua_de_costas_cama", "Mulher loira nua de costas sentada na cama; legenda 'You're going to start'"),
 (1861, "mulher_lingerie_rosa_apple_watch", "Homem com Apple Watch tocando mulher de lingerie rosa; legenda 'You're going to start sleeping'"),
 (1865, "stallone_this_was_the_milestone", "Stallone sério, olhando à câmera; legenda 'This was the milestone'"),
 (1879, "homem_mao_na_cabeca_permanent_loss", "Homem com a mão na cabeça; legenda 'permanent functional loss.'"),
 (1898, "mao_feminina_unhas_brancas_penis", "Mão feminina de unhas brancas; legenda 'and she'll stop offering.'"),
 (1905, "stallone_jennifer_golden_globes", "Stallone e Jennifer em evento (Golden Globes), tom laranja; legenda 'thought he was going to die'"),
 (1915, "casal_dormindo_costas_viradas", "Casal dormindo de costas um para o outro; legenda 'who turned into friends.'"),
 (1919, "mulher_cama_sem_expectativa", "Mulher na cama de braços cruzados; legenda 'without expectation,'"),
 (1924, "caught_in_the_act_40_year_old_woman", "Vídeo 'Caught in the Act! 40-Year-Old Woman Caught Cheating' (marido flagra esposa com outro homem); legenda 'She's going to be obsessed'"),
 (1929, "camera_seguranca_mulher_entrando_carro", "Câmera de segurança: mulher entrando em carro à noite; legenda 'You won't have the strength.'"),
 (1932, "lettering_we_call_this_surrender", "Dr. Attia; lettering vermelho 'WE CALL THIS SURRENDER'"),
 (1937, "cam2_casal_rua_bone", "Câmera 'CAM 2': mulher de braço dado com homem de boné; legenda 'you can bring you back whole.'"),
 (1983, "stallone_retrato_that_afternoon", "Retrato de Stallone sorrindo; legenda 'that afternoon'"),
 # bloco 15 — mecanismo da solução I
 (2000, "corte_penis_toxic_plaques_lupa", "Corte 3D do pênis com lupa sobre placas tóxicas; legenda 'toxic plaques, you'"),
 (2010, "idoso_cozinha_pb_pulling_out", "Idoso na cozinha em preto e branco; legenda 'Because pulling out'"),
 (2014, "histologia_type_iii_to_type_i", "Histologia 'Type III → Type I' com placa; legenda 'in three months.'"),
 (2019, "lettering_hydrolyzed_collagen_pote_cavalo", "Pote 'Hydrolyzed Collagen' com cavalos ao fundo; lettering 'HYDROLYZED COLLAGEN'"),
 (2023, "pote_bovine_collagen", "Pote 'Bovine Collagen'; legenda 'It's not bovine collagen.'"),
 (2026, "pote_marine_collagen", "Pote 'Marine Collagen'; legenda 'It's not marine collagen.'"),
 (2028, "estomago_acido_gastrico_destroi", "Animação de parede do estômago destruindo fibras; legenda 'They're destroyed by gastric acid'"),
 (2036, "tendoes_percheron_bandeja", "Tendões de cavalo em bandeja com ficha 'Percheron Stallion — Lexington'; legenda 'from the tendons of purchase'"),
 (2038, "tendao_percheron_na_mao", "Tendão de cavalo segurado na mão sobre ficha; legenda 'in Lexington.'"),
 (2050, "pote_hydrolyzed_collagen_percheron_stallion", "Pote 'Hydrolyzed Collagen from the Percheron Stallion — Type I & III — 500g'; legenda 'hydrolyzed collagen'"),
 (2058, "garanhao_percheron_preto_baia", "Garanhão Percheron preto na baia; legenda 'the same as at five.'"),
 (2073, "corpo_3d_azul_laranja_your_body", "Corpo 3D azul com área laranja; legenda 'your body at the same time.'"),
 (2078, "corte_vaso_fragmentos_30_years", "Corte 3D de corpo cavernoso; legenda 'some over 30 years into fragments'"),
 (2089, "frasco_urina_lexington_lab_dia_3", "Frasco de urina escura com ficha 'Lexington Lab — Penile Fibrosis Clearance Study / Day 3 urine darkening'; legenda 'The patient's'"),
 (2093, "frasco_urina_fragments_leaving_the_body", "Frasco de urina com laudo; legenda 'fragments leaving the body.'"),
 (2128, "mapa_kentucky_lexington", "Mapa dos EUA destacando Kentucky; legenda 'you'd have to go to Kentucky,'"),
 (2135, "equipamento_enzimatico_inox", "Equipamento de processamento enzimático em inox; legenda 'the enzymatic'"),
 (2138, "equipamento_costs_1_400_000", "Tanques de inox; legenda 'that costs $1,400,000 per unit.'"),
 (2142, "there_are_17_of_those_machines", "Linha de equipamentos industriais; legenda 'There are 17 of those machines'"),
 (2149, "pipeta_azul_lexington_17th", "Pipeta azul em tubos; legenda 'The 17th is in Lexington.'"),
 (2153, "tendoes_extract_in_the_state", "Tendões em bandeja; legenda 'extract in the state'"),
 (2162, "fda_food_and_drug_administration_tela", "Tela 'Food and Drug Administration'; legenda 'biological product,'"),
 (2166, "documento_fda_unregulated_biological_products", "Documento FDA 'Unregulated Biological Products — FDA Regulatory Classification'; legenda 'for retail sales since 1987.'"),
 (2168, "materia_fda_unregulated_1987", "Matéria 'FDA classifies that form as an unregulated biological product... prohibited by law for retail sale since 1987'"),
 (2175, "calendario_14_months", "Calendário com meses sobrepostos; legenda 'It took 14 months to develop'"),
 (2177, "gomas_azuis_a_gummy", "Gomas azuis translúcidas; legenda 'a gummy'"),
 (2180, "fda_registration_certificate_21_cfr_111", "Certificado 'FDA Registration Certificate' e logo FDA; legenda 'FDA category 21 CFR 111,'"),
 (2190, "pipeta_luva_azul_broto_verde", "Pipeta pingando em tubo com broto verde; legenda 'of the raw extracts efficacy.'"),
 (2193, "notas_dolar_vermelho_219000", "Notas de dólar em tom vermelho; legenda '$219,000'"),
 (2195, "cifrao_dourado_bioequivalence", "Cifrão dourado sobre dólares; legenda 'in bioequivalence testing.'"),
 (2207, "corte_penis_links_of_the_toxic_plaques", "Corte 3D do pênis com lupa; legenda 'links of the toxic plaques.'"),
 (2210, "cedars_sinai_medical_imaging_day_1_day_30", "Laudo 'Cedars-Sinai Medical Imaging — Patient #14 Lexington Pilot 2023 — Day 1 / Day 30 — Cavernous Volume +47%'"),
 (2237, "pote_collagen_cavalo_single_ingredient", "Pote de colágeno com cavalo ao fundo; legenda 'a single ingredient.'"),
 # bloco 16 — mecanismo da solução II–IV
 (2260, "lettering_liposomal_vitamin_c", "Animação de lipossoma; lettering 'LIPOSOMAL VITAMIN C.'"),
 (2268, "fibras_rosa_novas_new_fibers", "Animação de fibras rosa novas; legenda 'new fibers.'"),
 (2275, "copo_suco_laranja_you_ate_orange", "Copo com laranja; legenda 'You ate orange,'"),
 (2280, "estomago_azul_destroyed_at_80", "Animação de estômago azul; legenda 'is destroyed at 80%'"),
 (2292, "mucosa_intestinal_lipossoma", "Animação de lipossoma na mucosa intestinal; legenda 'to the intestinal mucosa.'"),
 (2306, "glifosato_pulverizacao_vermelha", "Pulverização em tom vermelho; legenda 'Glyphosate'"),
 (2310, "paes_doces_every_slice_of_bread", "Cesta de pães; legenda 'every slice of bread.'"),
 (2318, "frasco_pycnogenol_casca_pinheiro", "Frasco 'Pycnogenol' com casca de pinheiro e estudo 'Oxidative Fibrosis / 21 clinical studies'; legenda 'concentrated extract'"),
 (2328, "pycnogenol_ocupa_sitio_vaso", "Animação: Pycnogenol ocupando sítio no vaso; legenda 'Pycnogenol occupies'"),
 (2334, "armadura_dourada_layer_of_armor", "Animação de escudo dourado sobre fibras; legenda 'is a layer of armor'"),
 (2341, "fibras_douradas_being_cleaned_out", "Fibras douradas com glifosato verde sendo limpo; legenda 'being cleaned out'"),
 (2347, "corte_vaso_dissolve_scar", "Corte 3D com cicatriz dissolvendo; legenda 'because even with dissolve scar,'"),
 (2350, "corpo_3d_receptores_signal", "Corpo 3D azul com receptores iluminados; legenda 'your body needs a signal.'"),
 (2358, "lettering_tongkat_ali_raiz", "Raízes de Tongkat Ali e planta; lettering 'TONGKAT ALI.'"),
 (2381, "attia_dissolve_regenerate", "Dr. Attia; legenda 'dissolve, regenerate,'"),
 (2399, "broll_five_days_91_of_patients", "B-roll pornô; legenda 'five days, 91% of patients'"),
 (2420, "broll_average_growth_2_to_4in", "B-roll pornô; legenda 'Average growth between 2 to 4in'"),
 (2426, "attia_thats_the_real_timeline", "Dr. Attia; legenda 'That's the real timeline in days,'"),
 # bloco 17 — o primeiro homem
 (2439, "frasco_vidro_escuro_bolsa_termica", "Frasco de vidro escuro em bolsa térmica com gelo; legenda 'jar inside the inner'"),
 (2441, "frasco_escuro_pocket_of_my_coat", "Frasco escuro lacrado em bolsa térmica (-18°C); legenda 'pocket of my coat, sealed,'"),
 (2449, "whitfield_farms_placa_dono_cavalo", "Placa 'Whitfield Farms — Kentucky's largest private Percheron breeding farm' com o dono e cavalo; legenda 'by the owner of Whitfield'"),
 (2451, "whitfield_farms_placa_est_1987", "Placa 'Whitfield Farms Est. 1987' com cavalo Percheron; legenda 'private purchaser'"),
 (2453, "fazenda_whitfield_cavalo_celeiro", "Fazenda com celeiro vermelho e cavalo Percheron; legenda 'on breeding farm in Kentucky.'"),
 (2459, "lettering_costs_11000_to_produce", "Notas de dólar com gráfico; lettering vermelho 'COSTS $11,000 TO PRODUCE.'"),
 (2466, "attia_e_stallone_ao_telefone_split", "Tela dividida: Dr. Attia e Stallone ao telefone; legenda 'I told him,'"),
 (2486, "relogio_seven_in_the_morning", "Ponteiro de relógio; legenda 'seven in the morning,'"),
 (2492, "lipossoma_vit_c_amarelo", "Animação de lipossoma amarelo; legenda 'liposomal Vit C'"),
 (2494, "pycnogenol_pinha_po", "Pó de Pycnogenol com pinha; legenda 'Pycnogenol'"),
 (2496, "suco_de_laranja_copo", "Suco de laranja sendo despejado em copo; legenda 'in a glass of orange juice.'"),
 (2502, "stallone_pijama_cozinha_xicara", "Stallone de pijama na cozinha com xícara; legenda 'Pete, I just woke up hard.'"),
 (2521, "stallone_poltrona_mansao_piscina", "Stallone em poltrona de couro em frente à mansão com piscina; legenda 'I fucked Jennifer last night.'"),
 (2555, "stallone_poltrona_at_79_years_old", "Stallone na poltrona; legenda 'at 79 years old.'"),
 (2564, "stallone_poltrona_it_had_been_stolen", "Stallone na poltrona; legenda 'It had been stolen'"),
 (2573, "laudo_cedars_sinai_72_days_60_38", "Laudo 'Cedars-Sinai — 72 Days — Fibrosis Quantification 60% → 38%'; legenda 'showing fibrosis'"),
 (2582, "attia_stallone_telefone_sly_authorized", "Tela dividida Dr. Attia e Stallone ao telefone; legenda 'Sly authorized this video'"),
]
