PICKS = [
 # bloco 18 — 37 voluntários / Novatech / nasce o Alpha Erec
 (2594, "quadro_active_patients_la_clinic_22_15", "Quadro branco 'Active Patients — LA Clinic: total seen this week 22 / referred by Marcus 15'; legenda 'from the L.A. clinic.'"),
 (2604, "broll_on_the_third_day", "B-roll pornô (mulher loira sorrindo); legenda 'on the third day.'"),
 (2629, "brandon_58_sofa_depoimento", "Brandon, 58 anos, de óculos e suéter no sofá; legenda 'I was on the list of the 37.'"),
 (2644, "brandon_i_had_3_5_more_inches", "Brandon no sofá; legenda 'I had 3.5 more inches.'"),
 (2652, "brandon_on_regular_guys_tom_laranja", "Brandon em tom laranja; legenda 'on regular guys.'"),
 (2667, "corte_penis_with_toxic_plaques", "Corte 3D do pênis com placas; legenda 'with toxic plaques,'"),
 (2681, "laboratorio_erlenmeyer_capsulas", "Pesquisadora com erlenmeyer de cápsulas; legenda 'American pharmaceutical labs.'"),
 (2687, "viagra_cialis_trt_protese_colagem", "Colagem: comprimidos azuis, Cialis, frasco de TRT e prótese peniana; legenda 'viagra, cialis, trt prostheses.'"),
 (2698, "capsula_amarela_per_month_per_patient", "Cápsula amarela em fundo azul; legenda 'per month per patient.'"),
 (2703, "dinheiro_mascara_on_the_first_sale", "Notas de dólar e máscara cirúrgica; legenda 'on the first sale.'"),
 (2713, "wsj_bayer_24_billion_i_brought_everything", "Jornal WSJ 'Bayer Faces $24 Billion...'; legenda 'I brought everything'"),
 (2715, "infografico_bill_gates_the_23_buried_studies", "Infográfico 'Bill Gates Investments since 2022: $11.4 billion across 5 fronts'; legenda 'the 23 buried studies,'"),
 (2718, "quadro_la_clinic_the_spreadsheets", "Quadro 'Active Patients — LA Clinic'; legenda 'The spreadsheets'"),
 (2746, "selo_fda_approved_check", "Selo 'Food and Drug Administration — FDA Approved' com check azul; legenda 'meeting 100% of the FDA's requirements'"),
 (2760, "chamada_audio_stallone_you", "Tela de chamada de áudio 'You / Stallone — Audio Only'; legenda 'I said:'"),
 (2769, "gomas_azuis_charge_what_it_costs", "Gomas azuis translúcidas; legenda 'charge what it costs to manufacture'"),
 (2771, "frasco_alpha_erec_cobra_and_thats_how", "Frasco Alpha Erec (Men's Performance Gummy, 30 gummies) com cobra; legenda 'And that's how'"),
 (2778, "clinicaltrials_gov_nct06182394", "Papel 'ClinicalTrials.gov — NCT06182394 — Double-Blind, Placebo-Controlled Trial... in Adult Males'; legenda 'under protocol NC 06182394,'"),
 (2780, "clinicaltrials_gov_tela_validated", "Monitor com ClinicalTrials.gov NCT06182394 'VALIDATED'; legenda 'under protocol NC 06182394,'"),
 (2782, "cedars_sinai_validation_confirmed", "Documento 'Cedars-Sinai Medical Center — Validation Confirmed'; legenda 'validated by Cedars-Sinai'"),
 (2784, "university_of_kentucky_validation_confirmation", "Documentos 'Validation Confirmation' Cedars-Sinai e University of Kentucky; legenda 'and the University of Kentucky.'"),
 (2787, "quadro_94_measurable_functional_reversal", "Quadro '94% Measurable Functional Reversal' com gráficos; legenda 'I got the first spreadsheet 94%'"),
 (2789, "painel_94_post_intervention_day_127", "Painel '94% Measurable Functional Reversal — post-intervention day 127, +41% from baseline'; legenda 'measurable functional reversal,'"),
 (2807, "voluntario_anonimo_rosto_borrado_sofa", "Voluntário anônimo com rosto borrado no sofá; legenda 'Five days'"),
 # bloco 19 — apresentação do Alpha Erec
 (2814, "frasco_alpha_erec_fogo_fibrosis", "Frasco Alpha Erec em fundo de fogo; legenda 'fibrosis of cavernous tissue'"),
 (2824, "tres_frascos_alpha_erec_manufactured_by_novatech", "Três frascos Alpha Erec; legenda 'Manufactured by Novatech'"),
 (2829, "lettering_100_safe_verde", "Dr. Attia; lettering verde '100% SAFE'"),
 (2832, "lettering_no_prescription", "Dr. Attia; lettering verde 'NO PRESCRIPTION.'"),
 (2845, "attia_sly_had_60_fibrosis_at_79", "Dr. Attia; legenda 'Sly had 60% fibrosis at 79.'"),
 (2852, "ficha_current_trial_1800_subjects_94", "Ficha 'Current Trial — Enrolled Subjects: 1,800 — Age range 35-70' e nota '94%'; legenda 'The 1800 in the current'"),
 (2856, "lettering_it_worked_in_94_so_far", "B-roll pornô; lettering verde 'IT WORKED IN 94% SO FAR.'"),
 (2868, "hemacias_that_attacks", "Hemácias em vaso; legenda 'that attacks'"),
 (2871, "vaso_fibrose_tissue_at_the_root", "Interior do vaso com fibrose; legenda 'tissue at the root.'"),
 (2879, "corpo_3d_figado_more_than_that", "Corpo 3D com fígado iluminado; legenda 'More than that,'"),
 (2902, "lettering_dissolve_amarelo", "Fundo escuro; lettering amarelo 'DISSOLVE'"),
 (2910, "frasco_alpha_erec_cobra_at_the_same_time", "Frasco Alpha Erec com cobra; legenda 'at the same time'"),
 (2922, "lexington_skyline_aereo", "Vista aérea de Lexington; legenda 'tendons is only'"),
 (2931, "gomas_azuis_one_gummy_in_the_morning", "Gomas azuis; legenda 'you take one gummy in the morning'"),
 (2942, "estomago_azul_because_the_gastric", "Animação de estômago azul com goma; legenda 'because the gastric'"),
 (2945, "estomago_azul_less_hostile", "Estômago azul com partículas; legenda 'stomach is less hostile'"),
 (2951, "mao_sem_injecao", "Mão segurando algo pequeno; legenda 'no injection,'"),
 (2953, "homem_ansioso_no_having_to_time_it", "Homem de cabeça baixa; legenda 'no having to time it'"),
 (2958, "frasco_alpha_erec_caixa_entrega", "Mão tirando frasco Alpha Erec de caixa de papelão; legenda 'AlphaErec works'"),
 (2961, "homem_acordando_you_wake_up", "Homem bocejando; legenda 'You wake up,'"),
 (2968, "frasco_alpha_erec_laboratorio", "Frasco Alpha Erec em bancada de laboratório; legenda 'AlphaErec is manufactured by'"),
 (2976, "frasco_alpha_erec_cfr_111", "Frasco Alpha Erec em laboratório; legenda 'CFR 111'"),
 (2983, "frasco_alpha_erec_fogo_100_safe", "Frasco Alpha Erec em fogo; legenda '100% safe'"),
 (2986, "cientista_oculos_100_free_of_gmos", "Cientista de jaleco com pipeta; legenda '100% free of GMOs.'"),
 (2990, "caixa_viagra_pfizer_no_dependency", "Caixa e blister de Viagra Pfizer; legenda 'No dependency.'"),
 (2997, "figado_3d_no_hepatic_impact", "Fígado 3D azul; legenda 'No hepatic impact.'"),
 (3001, "medico_frasco_amarelo_medical_prescription", "Médico sorridente com frasco; legenda 'medical prescription.'"),
 (3012, "homem_grisalho_frasco_alpha_erec_jardim", "Homem grisalho de óculos segurando frasco Alpha Erec no jardim; legenda 'there's no vasoconstriction'"),
 (3016, "esqueleto_3d_coracao_prostata", "Animação 3D de coração e próstata; legenda 'It doesn't matter'"),
 (3021, "caixa_cialis_tadalafil", "Caixas de Cialis (tadalafil); legenda 'cialis,'"),
 (3028, "idoso_barba_branca_it_doesnt_matter", "Idoso de barba branca; legenda 'It doesn't matter'"),
 (3048, "seringa_luva_azul_blue_pill_trt", "Seringa em luva azul; legenda 'Blue pill TRT,'"),
 (3075, "lettering_dude_try_it_theres_nothing_else", "Dr. Attia; lettering 'DUDE TRY IT. THERE'S NOTHING ELSE THAT'S GOING TO WORK'"),
 # bloco 20 — celebridades
 (3078, "arnold_selfie_im_arnold", "Arnold Schwarzenegger em selfie, tom laranja; legenda 'I'm Arnold,'"),
 (3086, "arnold_frasco_alpha_erec_60_days", "Arnold Schwarzenegger de camisa azul segurando frasco Alpha Erec; legenda 'I took AlphaErec for 60 days'"),
 (3103, "attia_the_second_one_to_accept", "Dr. Attia; legenda 'The second one to accept'"),
 (3121, "van_damme_gorro_oculos_cachorro", "Jean-Claude Van Damme de gorro e óculos com cachorro; legenda 'Kegel exercise, nothing.'"),
 (3143, "van_damme_it_works", "Van Damme em selfie; legenda 'works, it works.'"),
 (3153, "ray_e_diane_holloway_foto", "Ray e Diane Holloway em evento; legenda 'Diane Holloway'"),
 (3195, "ray_holloway_frasco_alpha_erec", "Ray Holloway (62) segurando frasco Alpha Erec"),
 # bloco 21 — escassez e oferta
 (3208, "kit_alpha_erec_caixa_67", "Caixa com frascos Alpha Erec e número '67' em neon vermelho; legenda 'from this page'"),
 (3214, "cavalo_branco_tratadora_extraction_capacity", "Tratadora de jaqueta laranja com cavalo branco; legenda 'the extraction capacity'"),
 (3225, "garanhao_percheron_preto_baia", "Garanhão Percheron preto na baia; legenda 'the Percheron horse'"),
 (3238, "lettering_it_works_like_this", "Dr. Attia; lettering 'IT WORKS LIKE THIS:'"),
 (3246, "kit_6_frascos_free_each_bottle_costs", "Kit de 6 frascos Alpha Erec com selos 'FREE'; legenda 'that means each bottle of AlphaErec costs'"),
 (3252, "frasco_alpha_erec_49_best_price", "Frasco Alpha Erec; lettering '$49 BEST PRICE'"),
 (3263, "lettering_and_permanent_results", "Hemácias; lettering 'AND PERMANENT RESULTS'"),
 (3268, "kit_3_frascos_if_you_prefer", "Kit de 3 frascos Alpha Erec em fogo; legenda 'if you prefer the three bottle kit'"),
 (3273, "kit_3_frascos_pay_for_two_get_one_free", "Kit de 3 frascos; legenda 'you pay only for two and get one completely free'"),
 (3280, "kit_6_frascos_recommended_six_months", "Kit de 6 frascos Alpha Erec; legenda 'that the recommended duration is six months'"),
 (3305, "kit_2_frascos_alpha_erec", "Kit de 2 frascos Alpha Erec; legenda 'in three months,'"),
 (3310, "kit_2_frascos_89_best_price", "Kit de 2 frascos; lettering '$89 BEST PRICE'"),
 (3326, "kit_6_frascos_and_theres_more", "Kit de 6 frascos; legenda 'and there's more'"),
 (3340, "johnny_sins_broll_a_technical_guide", "B-roll pornô com Johnny Sins; legenda 'a technical guide'"),
 (3354, "frasco_alpha_erec_laboratorio_because_i_saw", "Frasco Alpha Erec em laboratório; legenda 'because I saw what'"),
 (3358, "johnny_sins_depoimento_camisa_cinza", "Johnny Sins falando à câmera de camisa cinza; legenda 'who were leaving'"),
 (3381, "lettering_497_bonus", "Dr. Attia; lettering amarelo '$497'"),
 (3386, "capa_guide_seven_positions", "Capa 'Guide to the Seven Positions Every Woman Asks For'; legenda 'every woman asks for.'"),
 (3401, "capa_prolonged_orgasm_manual", "Capa 'Prolonged Orgasm Manual'; legenda 'The third bonus'"),
 (3411, "comprimidos_azuis_without_a_pill", "Comprimidos azuis; legenda 'without a pill,'"),
 (3418, "capa_lesbian_trick_map_of_female_pleasure", "Capa 'Lesbian Trick Map of Female Pleasure'; legenda 'The fourth bonus'"),
 (3441, "lettering_697_bonus", "Dr. Attia; lettering amarelo '$697'"),
 (3447, "consulta_zoom_attia_paciente", "Tela de Zoom: Dr. Attia e paciente; legenda 'Individual 45 minute'"),
 (3462, "homem_cartao_credito_sofa", "Homem no sofá segurando cartão de crédito; legenda 'And if you close'"),
 (3480, "colagem_4_bonus_3777", "Colagem dos 4 bônus (manual, posições, orgasmo, mapa) + ícone de ligação; lettering '$3777'"),
 (3489, "frasco_alpha_erec_60_day_guarantee", "Frasco Alpha Erec com selo '60 Day Guarantee — Money Back'; legenda 'if you don't notice your dick'"),
 (3496, "maos_laptop_you_send_an_email", "Mãos digitando em laptop; legenda 'you send an email'"),
 # bloco 22 — fechamento
 (3502, "stallone_i_authorize_this_video", "Stallone em selfie; legenda 'I authorize this video'"),
 (3525, "celular_mao_path_one", "Mão segurando celular, tom laranja; legenda 'Path one.'"),
 (3530, "hemacias_the_toxic_plaques", "Hemácias e vaso; legenda 'The toxic plaques'"),
 (3532, "casal_cama_costas_in_18_months", "Casal na cama de costas um para o outro (vista de cima); legenda 'In 18 months,'"),
 (3537, "homem_maos_na_cabeca_surrender", "Homem com as mãos na cabeça; legenda 'in ten years. Surrender.'"),
 (3539, "jantar_familia_idosos", "Jantar de família com idosos; legenda 'You're going to be'"),
 (3544, "lettering_its_not_going_to_be", "Lettering verde 'IT'S NOT GOING TO BE'"),
 (3554, "celular_encrypted_page", "Mãos no celular; legenda 'encrypted page'"),
 (3556, "caixa_papelao_porta_72_hours", "Caixa de papelão na porta; legenda 'and in 72 hours,'"),
 (3559, "fita_embalagem_no_name_on_the_label", "Fita de embalagem sendo aplicada; legenda 'with no name on the label'"),
 (3589, "stallone_gravata_borboleta_i_showed", "Stallone de gravata-borboleta; legenda 'I showed'"),
 (3591, "brandon_jardim_i_showed_brandon", "Brandon de suéter no jardim; legenda 'I showed Brandon,'"),
 (3596, "ray_e_diane_her_husband", "Ray e Diane Holloway; legenda 'her husband.'"),
 (3598, "arnold_i_showed_arnold", "Arnold Schwarzenegger; legenda 'I showed Arnold,'"),
 (3600, "robert_callahan_jaleco_laboratorio", "Robert Callahan de jaleco no laboratório Novatech; legenda 'I showed Robert,'"),
 (3618, "homem_grisalho_frasco_alpha_erec_other_american_men", "Homem grisalho de barba segurando frasco Alpha Erec; legenda 'other American men are'"),
 (3644, "homem_grisalho_praia_energy_from_your_40s", "Homem grisalho na praia; legenda 'Energy from your 40s'"),
 (3673, "kit_6_frascos_60_day_guarantee_green_button", "Kit de 6 frascos com selo '60 Day Guarantee'; legenda 'click the green button below this video'"),
 (3700, "documentos_every_piece_of", "Mãos com documentos; legenda 'Every piece of'"),
 (3734, "esferas_douradas_rebuild_new_type", "Esferas douradas; legenda 'Rebuild new type'"),
 (3754, "kit_6_frascos_do_it_once_close_the_cycle", "Kit de 6 frascos com selo de garantia; legenda 'do it once close the cycle'"),
 (3760, "casal_idoso_abraco_the_third", "Casal idoso abraçado; legenda 'The third is the one'"),
 (3766, "casal_jovem_jaqueta_jeans_youth", "Casal jovem de jaqueta jeans; legenda 'when you were still'"),
 (3785, "lettering_but_hes_there_whole", "Dr. Attia; lettering amarelo 'BUT HE'S THERE. WHOLE'"),
 (3792, "lettering_logic", "Lettering amarelo 'LOGIC'"),
 (3803, "attia_thank_you_for_watching", "Dr. Attia; legenda 'Thank you for watching.'"),
]
